name: Testes Automatizados + Confluence

on:
  workflow_dispatch: # Permite iniciar manualmente via GitHub UI

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Instalar dependências Maven
        run: mvn install

      - name: Executar testes Maven
        run: mvn test || true # Continua mesmo que os testes falhem

      - name: Capturar resultado dos testes
        run: cat target/surefire-reports/*.txt > resultado.txt || echo "Nenhum resultado encontrado" > resultado.txt

      - name: Upload do resultado dos testes
        uses: actions/upload-artifact@v3
        with:
          name: resultado_teste
          path: resultado.txt

      - name: Enviar resultado para Confluence
        env:

          CONFLUENCE_URL: "https://renatoarai.atlassian.net/wiki/rest/api/content/131084"
          CONFLUENCE_USER: "renatoarai@gmail.com"
          CONFLUENCE_API_TOKEN: ""

        run: |
          echo "Enviando resultado para Confluence..."
          curl -u "$CONFLUENCE_USER:$CONFLUENCE_API_TOKEN" -X PUT "$CONFLUENCE_URL" \
            -H "Content-Type: application/json" \
            --data "{\"type\":\"page\",\"title\":\"Resultados do Teste\",\"body\":{\"storage\":{\"value\":\"<pre>$(cat resultado.txt)</pre>\",\"representation\":\"storage\"}}}"
