name: Testes Automatizados + Confluence

on:
  workflow_dispatch: # Permite iniciar manualmente via GitHub UI

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Instalar dependências Maven
        run: mvn install

      - name: Executar testes Maven
        run: mvn test || true # Continua mesmo que os testes falhem

      - name: Capturar resultado dos testes
        run: cat target/surefire-reports/*.txt > resultado.txt || echo "Nenhum resultado encontrado" > resultado.txt

      - name: Upload do resultado dos testes
        uses: actions/upload-artifact@v3
        with:
          name: resultado_teste
          path: resultado.txt

      - name: Enviar resultado para Confluence
        env:
          CONFLUENCE_URL: "https://renatoarai.atlassian.net/wiki/spaces/~7120201ed0ba27ef7a42468acc4373be8b09e4/pages/131084/pagina01"
          CONFLUENCE_USER: "renatoarai@gmail.com"
          CONFLUENCE_API_TOKEN: "ATCTT3xFfGN04UD5ep6GMUgOv4jC4unk_-ghrMRZRbF8uCSLIzxgQJ-Zzf2_koTpYFUmDip7ha4V4tyc_9lvCMAebWxrF83GncGE0qTtxgr9hNZd8Q3eQTuBrHM7nQE_Nj_XGYCpACN_cymxJIR5EGPFTkFOOaiCx-rsqq0c24rJb1sVZVYk6zU=41EA33BE"
        run: |
          echo "Enviando resultado para Confluence..."
          curl -u "$CONFLUENCE_USER:$CONFLUENCE_API_TOKEN" -X PUT "$CONFLUENCE_URL" \
            -H "Content-Type: application/json" \
            --data "{\"type\":\"page\",\"title\":\"Resultados do Teste\",\"body\":{\"storage\":{\"value\":\"<pre>$(cat resultado.txt)</pre>\",\"representation\":\"storage\"}}}"
