name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Enviar saudação
        run: echo "Hello ${{ inputs.name }}"

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Instalar dependências
        run: mvn install

      - name: Executar testes
        run: mvn test || true # Garante que o workflow não falhe se houver erro nos testes

      - name: Salvar resultado do teste
        run: cat target/surefire-reports/*.txt > resultado.txt || echo "Nenhum resultado encontrado" > resultado.txt

      - name: Upload do resultado
        uses: actions/upload-artifact@v3
        with:
          name: resultado_teste
          path: resultado.txt
