name: Run Maven Tests

on:
  repository_dispatch:
    types: [run-maven-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v4

      - name: Configurar Java e Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Token configurado com sucesso!"

      - name: Print Test Execution Key
        run: echo "Test Execution Key: ${{ github.event.client_payload.testExecutionKey }}"

      - name: Run Maven Tests
        run: mvn clean test -DtestExecutionKey=${{ github.event.client_payload.testExecutionKey }}
