name: Run Maven Tests

on:
  repository_dispatch:
    types: [run-maven-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }} # Usa a branch enviada no payload

      - name: Run Maven Tests
        run: mvn clean test -DtestExecutionKey=${{ github.event.client_payload.testExecutionKey }} -Dusuario=${{ github.event.client_payload.usuario }}